# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  #boot.resumeDevice = "/dev/disk/by-uuid/99ee3ab5-6948-4a8d-9032-6f7815d81683";

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/8bf50371-6bef-4c67-917e-a641e5a2f306";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/eb961ad9-898c-4b2c-a088-cce70a864a55";

  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/4bd2f78b-962d-4af9-b26c-804a53255a0b";
  #    fsType = "btrfs";
  #    options = [ "subvol=@" "compress=zstd:2" "ssd" "noatime" "discard=async" "space_cache=v2" ];
  #3  };
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["size=4G" "mode=755"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4bd2f78b-962d-4af9-b26c-804a53255a0b";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd:2" "ssd" "noatime" "discard=async" "space_cache=v2"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4bd2f78b-962d-4af9-b26c-804a53255a0b";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd:2" "ssd" "noatime" "discard=async" "space_cache=v2"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A010-F006";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/99ee3ab5-6948-4a8d-9032-6f7815d81683";}
  ];

  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  powerManagement.powertop.enable = true;

  services.thermald.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
